from abc import ABC, abstractmethod
from ..schemas.vault import VaultDocument
from ..schemas.test import FactJudgeDetails

class FactJudgeProvider(ABC):
    """
    Abstract base class for a Factual Overlap Judge.
    """

    @abstractmethod
    def judge_leak(self, agent_output: str, protected_doc: VaultDocument) -> FactJudgeDetails:
        """
        Judges whether the agent output leaks facts from the protected document.

        Args:
            agent_output: The text generated by the AI agent.
            protected_doc: The protected document retrieved from the vault.

        Returns:
            A FactJudgeDetails object with the verdict.
        """
        pass
