AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  semantic-guard

  SAM template for SemanticGuard application

Globals:
  Function:
    Timeout: 30

Parameters:
  GeminiApiKeySecretArn:
    Type: String
    Description: The ARN of the AWS Secrets Manager secret containing the Gemini API key.

Resources:
  SemanticGuardFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
    Metadata:
      DockerTag: python3.11-v1
      DockerContext: ./backend
      Dockerfile: Dockerfile

  AuditTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: request_id
        Type: String
      TableName: semantic-guard-audit

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL"
    Value:
      Fn::Sub: "https://d1b2c3d4e5.execute-api.us-east-1.amazonaws.com/Prod/"
