from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any

class TestRequest(BaseModel):
    mode: str = Field(..., description="The behavior mode for the demo agent (e.g., 'leaky', 'obfuscated').")
    query: str = Field(..., description="The user query to be sent to the agent.")

class SemanticDetails(BaseModel):
    score: Optional[float] = Field(None, description="The semantic similarity score.")
    matched_document_id: Optional[str] = Field(None, description="The ID of the top matching document in the vault.")

class FactJudgeDetails(BaseModel):
    is_derived: bool = Field(False, description="Whether the fact judge found a factual overlap.")
    confidence: Optional[float] = Field(None, description="The confidence score from the fact judge.")
    matched_facts: List[str] = Field(default_factory=list, description="The specific facts that were found to overlap.")
    reason: Optional[str] = Field(None, description="The reasoning provided by the fact judge.")

class DecisionDetails(BaseModel):
    action: str = Field(..., description="The final decision: 'ALLOW', 'BLOCK', or 'REVIEW'.")
    reason: Optional[str] = Field(None, description="The reason for the decision.")

class TestResponse(BaseModel):
    request_id: str = Field(..., description="The unique ID for this test request.")
    mode: str = Field(..., description="The agent mode used for the test.")
    query: str = Field(..., description="The original user query.")
    agent_output: str = Field(..., description="The raw output generated by the agent.")
    semantic: SemanticDetails = Field(..., description="Details from the semantic similarity scan.")
    fact_judge: FactJudgeDetails = Field(..., description="Details from the factual overlap judge.")
    decision: DecisionDetails = Field(..., description="The final decision made by the engine.")
    lineage_tag: Optional[str] = Field(None, description="The lineage tag of the matched protected data, if any.")
    processing_ms: float = Field(..., description="Total processing time in milliseconds.")
    timestamp: Optional[str] = Field(None, description="UTC ISO-8601 timestamp of when the backend received the request. Additive field, absent on historical records predating it.")
    requester_ip: Optional[str] = Field(None, description="Client IP captured server-side from the connection (or a trusted proxy header, only if explicitly configured). Absent on historical records predating it.")

